name: Build Artifacts

on:
  workflow_dispatch:
  
  schedule:
    - cron: '20 1,12,7 * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 16
      uses: actions/setup-java@v1
      with:
        java-version: 16
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Set up keystore
      run: |
        echo "${{ secrets.KEYSTORE_BASE64 }}" > keystore.txt
        base64 --decode keystore.txt > bekeystore.jks
    - name: Create artifacts
      env:
        keystore_password: ${{ secrets.KEYSTORE_PASSWORD_SECRET }}
        keystore_alias_password: ${{ secrets.KEYSTORE_PASSWORD_SECRET }}
        keystore_alias: hex
      run: |
        git clone --depth=1 --branch=erekir https://github.com/Anuken/Mindustry
        cd Mindustry
        sed -i 's/applicationId "io.anuke.mindustry"/applicationId "io.anuke.mindustry.be.hex"/g' android/build.gradle
        sed -i 's/"io.anuke.mindustry"/"io.anuke.mindustry.be.hex"/g' android/AndroidManifest.xml
        sed -i 's/Mindustry/MDTBEv7/g' android/res/values/strings.xml
        ./gradlew pack
        ./gradlew desktop:dist server:dist android:assembleRelease -Pbuildversion=${RELEASE_VERSION} -PversionType=bleeding-edge-hex --stacktrace
        mv desktop/build/libs/Mindustry.jar desktop/build/libs/Mindustry-BE-v7-Desktop-${RELEASE_VERSION}.jar
        mv server/build/libs/server-release.jar server/build/libs/Mindustry-BE-v7-Server-${RELEASE_VERSION}.jar
        ls -R android/build/outputs/apk
        mv android/build/outputs/apk/release/android-release.apk android/build/outputs/apk/release/Mindustry-BE-v7-Android-${RELEASE_VERSION}.apk
    - name: Upload desktop artifacts
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: Mindustry/desktop/build/libs/Mindustry-BE-v7-Desktop-${{ env.RELEASE_VERSION }}.jar
        tag: ${{ github.ref }}
    - name: Upload server artifacts
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: Mindustry/server/build/libs/Mindustry-BE-v7-Server-${{ env.RELEASE_VERSION }}.jar
        tag: ${{ github.ref }}
    - name: Upload Android artifacts
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: Mindustry/android/build/outputs/apk/release/Mindustry-BE-v7-Android-${{ env.RELEASE_VERSION }}.apk
        tag: ${{ github.ref }}
